language: csharp
dist: trusty
os: linux
solution: RandomNumberGame.sln
mono: none
dotnet: 1.0.0-preview2-003121

script:
    - dotnet test ./tests/RNGTest -c Release
    - dotnet build ./RandomNumberGame.csproj -c Release